services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
  healthcare-api:
    image: "healthcare/api:0.0.1"
    container_name: patient-healthcare-api
    env_file:
      - .env
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    command: /usr/src/app/healthcare/entrypoint.sh ${HOST} ${PORT}
    volumes:
      - ./static_data:/var/www/healthcare.com/staticfiles
    restart: unless-stopped
    depends_on:
      - postgres
  reverse-proxy:
    image: "healthcare/api-reverse-proxy:0.0.1"
    container_name: healthcare-api-reverse-proxy
    env_file:
      - .env
    build: ./reverse_proxy
    ports:
      - ${REVERSE_PROXY_PORT}:${REVERSE_PROXY_PORT}
    volumes:
      - ./reverse_proxy/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./static_data:/var/www/healthcare.com/staticfiles
    restart: unless-stopped
    depends_on:
      - healthcare-api

volumes:
  db_data:
  static_data:
