# Generated by Django 5.1.4 on 2025-01-03 22:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resourceType', models.CharField(max_length=10)),
                ('name', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), size=3)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=50, null=True)),
                ('address', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), size=3)),
                ('telecom', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), size=3)),
                ('active', models.BooleanField(default=True, null=True)),
                ('deceasedBoolean', models.BooleanField(default=False, null=True)),
                ('maritalStatus', models.JSONField(default=dict, null=True)),
                ('multipleBirthInteger', models.IntegerField(default=1, null=True)),
                ('photo', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, null=True), null=True, size=3)),
                ('contact', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, null=True), null=True, size=3)),
                ('communication', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, null=True), null=True, size=3)),
                ('generalPractitioner', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, null=True), null=True, size=3)),
                ('managingOrganization', models.JSONField(default=dict, null=True)),
                ('link', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, null=True), null=True, size=3)),
            ],
        ),
    ]
